version: '3.8'

services:
  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-scoring-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
      - celery
    networks:
      - resume-scoring-network

  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: resume-scoring-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - resume-scoring-network

  # Redis for Celery
  redis:
    image: redis:7-alpine
    container_name: resume-scoring-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - resume-scoring-network

  # Celery Worker (Optional - for background tasks)
  celery:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-scoring-celery
    command: celery -A app.celery_app worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      - db
      - redis
    networks:
      - resume-scoring-network

  # Flower - Celery Monitoring
  flower:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-scoring-flower
    command: celery -A app.celery_app flower --port=5555
    ports:
      - "5555:5555"
    depends_on:
      - db
      - redis
      - celery
    networks:
      - resume-scoring-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  resume-scoring-network:
    driver: bridge 